my_django_stuff/revampedCalc/calc/urls.py
from django.conf.urls import url

from . import views

app_name = 'calc'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<test>[0-9]+)/result/$', views.result, name='result'),
    
]

my_django_stuff/revampedCalc/calc/views.py
#from django.shortcuts import render

from django.http import HttpResponse

from django.http import HttpResponse
from .models import Question
from django.shortcuts import render, render_to_response
from math import pi
import numpy as np

def index(request):
    #return render(request, 'index.html')
    #return render(request, 'calc/index.html')
    return render_to_response('calc/index.html')


def result(request, test):
    if request.method == "GET":
        con_lvl= request.GET['conLevel']
        me = request.GET['marginError']
        pop = request.GET['popSize']

    tuple = sample_size_calc(float(con_lvl), float(me), float(pop))
    return render(request, 'calc/result.html', {
        'conLevel': con_lvl,
        'marginError': me,
        'popSize' : pop,
        'tuple': tuple,
        'ss': ss
#        'wastedSpace': tuple[1],
#        'numOfCans': tuple[0]
    })

def sample_size_calc(con_lvl, me, pop_size=None):
    P=.5

    if con_lvl == 95 or con_lvl == .95:
        con_lvl = 1.96 # zscore

    if con_lvl == 99 or con_lvl == .99:
        con_lvl = 2.58 # zscore

    ss = np.ceil(con_lvl**2 *P *(1-P)/me**2)

    if pop_size is None:
        print("Minimum sample size you need is: ", ss)
        return ss

    else:
        ss = np.ceil(ss/(1+(ss/pop_size)))
        print("Minimum sample size you need is: ", ss)
        return ss

my_django_stuff/revampedCalc/calc/templates/calc/index.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Minimum Population Size</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>


    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h1 class="section-heading">Calculate by entering Confidence level,
                    Margin of error and Population Size</h1>
                    <hr class="light">


            <div style="font-family: Verdana; font-weight: normal; font-size: 20px; color: gray;">
            <form action="{% url 'calc:result' 100 %}" method="get">
            {% csrf_token %}

                <label style="font-weight: normal;"> Confidence Level </label>

                <input type="text" name="conLevel" id="02" value="" /><br>
                <label style="font-weight: normal;">Margin of Error: </label>

                <input type="text" name="marginError" id="03" value="" /><br>
                <label style="font-weight: normal;">Population Size: </label>

                <input type="text" name="popSize" id="04" value="" /><br>

                <hr class="light">
                <input type="submit" value="Crunch The Numbers" />
            </form>
            </div>


                </div>
            </div>
        </div>
    </section>








    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/creative.min.js' %}"></script>

</body>

</html>

my_django_stuff/revampedCalc/calc/templates/calc/result.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Calculus Canning Calculator</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top"> =D </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">RESULTS</h1>
                <hr>

                	<p>
					<label style="color: white;">Population Size needed  {{ ss }}</label> <br>

<!--

					<label style="color: white;">Can Radius: {{ canRadius }}</label> <br><br>

					<label style="color: white;">Number of cans: {{ numOfCans}} </label><br>
					<label style="color: white;">Wasted Space: {{ wastedSpace}} </label><br>
-->
                	</p>

            </div>
        </div>
    </header>



</body>

</html>